baseURL = 'https://natnater.com/'
languageCode = 'en-us'
title = "Natnater"
theme = "hugo-theme-cleanwhite"
[params]
  subtitle = "When you're here, you're here."
  [params.contact]
    email = 'njdevender+blog@gmail.com'

